src/order/urls.py
from django.contrib import admin
from django.urls import path, include
from order import views

app_name= 'order'
urlpatterns = [
    path('add_to_cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('delete_from_cart/<int:pk>/', views.DeleteFromCart.as_view(), name='delete_from_cart'),
    path('update_cart/', views.UpdateCart.as_view(), name='update_cart'),
    path('info/', views.ContactFormView.as_view(), name='info'),
    
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from forecast import views
import reference


urlpatterns = [
    path('admin/', admin.site.urls),
    path('navbar/', views.NavBar.as_view()),
    path('forecast/', views.show_forecast_view),
    path ('main_page/', views.MainPage.as_view()),
    path ('book_list/', views.BookPage.as_view()),
    path ('book_search/', views.BookSearch.as_view()),
    path('book/<int:pk>/', views.BookDetailView.as_view()),
    path('/book/<int:pk>/', views.BookDetailView.as_view()),
    path ('main_page/', views.MainPage.as_view()),
    path ('map_page/', views.MapPage.as_view()),
    #path ('book_add/', views.book_add_view),
    #path ('map_page/', views.BookEdit.as_view()),
    path ('book_add/', views.BookAdd.as_view()),
    path ('new_arrivals/', views.NewArrivals.as_view()),
    path ('bestsellers/', views.Bestsellers.as_view()),
    path ('catalogue/', views.Catalogue.as_view()),
    path('ref/', include(('reference.urls', 'reference'), namespace ='ref')),
    path('order/', include('order.urls', namespace ='order')), 
    path ('main_page/thanks/', views.MainPageThanks.as_view()),
   
]

src/forecast/models.py
from datetime import datetime
from email.policy import default
from random import choices
from django.db import models
from django.utils import timezone
from reference.models import Publisher, Author, Seria

ACTIVE= 'Active'
INACTIVE= 'Inactive'

 
class Genre(models.Model):
    #NONFICTION
    ART = 'Art/architecture'
    AUTOBIOGRAPHY = 'Autobiography'
    BIOGRAPHY ='Biography'
    BUSINESS = 'Business'
    CRAFTS = 'Crafts'
    COOKBOOK = 'Cookbook'
    DIARY = 'Diary'
    DICTIONARY = 'Dictionary'
    ENCYCLOPEDIA = 'Encyclopedia'
    GUIDE = 'Guide'
    HEALTH = 'Health'
    HISTORY = 'History'
    HOME = 'Home'
    HUMOR= 'Humor'
    JOURNAL= 'Journal'
    MATH ='MATH'
    MEMOIR = 'Memoir'
    PHILOSOPHY = 'Philosophy'
    PRAYER = 'Prayer'
    RELIGION = 'Religion'
    TEXTBOOK= 'Textbook'
    TRUE_CRIME = 'True crime'
    REVIEW = 'Review'
    SCIENCE = 'Science'
    SELF = 'Self'
    SPORTS = 'Sports'
    TRAVEL = 'Travel' 
    OTHER = 'Other'
    #Fiction
    ACTION = 'Action'
    ALTERNATIVE = 'Alternate history'
    ANTOLOGY = 'Anthology'
    CHIK = 'Chick lit'
    CHILD = 'Childrens'
    CLASSIC = 'Classic'
    COMIC = 'Comic book'
    COMING = 'Coming-of-age'
    CRIME = 'Crime'
    DRAMA = 'Drama'
    FAIRYTALE = 'Fairytale'
    FANTASY = 'Fantasy'
    GRAPHIC = 'Graphic novel'
    HISTORICAL = 'Historical fiction'
    HORROR = 'Mystery'
    MYSTERY = 'Comic book'
    PARANORMAL = 'Paranormal romance'
    PICTURE = 'Picture book'
    POETRY = 'Poetry'
    POLITICAL = 'Political thriller'
    ROMANCE = 'Romance'
    SATIRE = 'Satire'
    SCI_FI = 'Science fiction'
    SHORTS = 'Short story'
    SUSPENSE = 'Suspense'
    THRILLER = 'Thriller'
    WESTERN = 'Thriller'
    YOUNG_ADULT = 'Young adult'
   
    GENRE_CHOICES = [
        ('Nonfiction', (
            (ART,'Art/architecture'), (AUTOBIOGRAPHY,'Autobiography'), (BIOGRAPHY,'Biography'), (BUSINESS, 'Business/economics'),
            (CRAFTS, 'Crafts/hobbies'), (COOKBOOK, 'Cookbook'), (DIARY, 'Diary'), (DICTIONARY,'Dictionary'), 
            (ENCYCLOPEDIA, 'Encyclopedia'), (GUIDE, 'Guide'), (HEALTH, 'Health/fitness'), (HISTORY, 'History'), (HOME, 'Home and garden'),
            (HUMOR, 'Humor'), (JOURNAL, 'Journal'), (MATH, 'Math'), (MEMOIR, 'Memoir'), (PHILOSOPHY, 'Philosophy'),
            (PRAYER,'Prayer'),(RELIGION,'Religion, spirituality, and new age'), (TEXTBOOK,'Textbook'), (TRUE_CRIME,'True crime'),
            (REVIEW, 'Review'), (SCIENCE, 'Science'), (SELF, 'Self help'),
            (SPORTS, 'Sports and leisure'), (TRAVEL, 'Travel'), (OTHER, 'Other')
        )),
    
        ('Fiction', (
            (ACTION,'Action and adventure'),(ALTERNATIVE, 'Alternate history'), (ANTOLOGY, 'Anthology'), (CHIK, 'Chick lit'), 
            (CHILD, 'Childrens'), (CLASSIC, 'Classic'), (COMIC, 'Comic book'), (COMING, 'Coming-of-age'), (CRIME, 'Crime'), 
            (DRAMA, 'Drama'), (FAIRYTALE, 'Fairytale'), (FANTASY, 'Fantasy'), (GRAPHIC, 'Graphic novel'), (HISTORICAL, 'Historical fiction'),
            (HORROR, 'Horror'), (MYSTERY, 'Mystery'), (PARANORMAL, 'Paranormal romance'), (PICTURE, 'Picture book'), (POETRY, 'Poetry'),
            (POLITICAL, 'Political thriller'), (ROMANCE, 'Romance'), (SATIRE, 'Satire'), (SCI_FI, 'Science fiction'), (SHORTS, 'Short story'),
            (SUSPENSE, 'Suspense'), (THRILLER, 'Thriller'),(WESTERN, 'Western'), (YOUNG_ADULT, 'Young adult'), (OTHER, 'Other')
           
        )),
        
        ('unknown', 'Unknown'),
    ]
    genre = models.CharField(
            max_length=20,
            choices=GENRE_CHOICES,
            default=OTHER,
    )
    def __str__(self) -> str:
         return self.genre

class Cover(models.Model):
    HARD = 'Hard cover'
    SOFT = 'Soft cover'
    OTHER = 'Other cover'
    COVER_CHOICES = [(HARD,'Hard cover'),
            (SOFT,'Soft cover'),
            (OTHER, 'Other')]

    cover = models.CharField(
            max_length=20,
            choices=COVER_CHOICES,
            default=OTHER,
    )
    
    def __str__(self) -> str:
         return self.cover

class AgeRestriction (models.Model):
    NOT_RESTRICTED = 'Without restrictions' 
    ADULT = '18+'
    TEENS = '12+'
    KIDS = '6+'
    TODDLERS = '1+'
    AGE_RESTRICT_CHOICES = [
            (NOT_RESTRICTED,'Without restrictions'),
            (ADULT,'18+'),
            (TEENS, '12+'),
            (KIDS, '6+'),
            (TODDLERS,'1+')]

    age_restriction = models.CharField(
            max_length=20,
            choices=AGE_RESTRICT_CHOICES,
            default=ADULT,
    )
    
    def __str__(self) -> str:
         return self.age_restriction


class Book(models.Model):
     import datetime
     name = models.CharField(max_length=150)
     authors = models.ManyToManyField('reference.Author', default='an author')
     image = models.ImageField(upload_to='src/static/imagination', height_field=None, width_field=None, max_length=100, default= "img.jpeg")
     price = models.DecimalField(verbose_name = "price", blank=False, default=10.00, decimal_places=2, max_digits=8)
     genre = models.CharField(choices=Genre.GENRE_CHOICES,max_length=120)
     publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
     #seria=models.ForeignKey(Seria, on_delete=models.CASCADE, blank=True, null=True, default='a seria')
     pages = models.IntegerField(blank=False, default=0)
     cover = models.CharField(choices=Cover.COVER_CHOICES, max_length=120, default='Other')
     format = models.CharField(help_text="Please use the following format: width(cm) x length(cm): ",max_length=5, blank=True, null=True)
     date_published = models.DateField(blank=False, default=datetime.date(1990, 1, 1))
     isbn = models.CharField(max_length=40, default='000-000-0000-00-0')
     weight = models.IntegerField(default='0')
     age_restriction = models.CharField(choices=AgeRestriction.AGE_RESTRICT_CHOICES, max_length=402, default='18+')
     items_available = models.IntegerField(blank=False, default=0)
     order_status = models.CharField(choices=[(ACTIVE,'Active'), (INACTIVE,'Inactive')], max_length=40, default='Inactive')
     rate = models.DecimalField(decimal_places=2, max_digits= 3, blank=True, null=True)
     created = models.DateTimeField(editable=False, default=datetime.datetime.now())
     modified = models.DateTimeField(default=datetime.datetime.now())
     description = models.TextField(blank=True, null=True)

     def save(self, *args, **kwargs):
        import datetime
        if not self.id:
            self.created = datetime.datetime.now()
        self.modified = datetime.datetime.now()
        return super(Book, self).save(*args, **kwargs)


     def __str__(self) -> str:
         return self.name
    
     def get_absolute_url(self):
         return "/book/%i/" % self.id

     def get_success_url(self):
        return f"/book/%i/" %self.id

src/forecast/forms.py
from django import forms
from django.db import models
from datetime import datetime
from forecast import models

class AddBookForm(forms.Form):

    name=forms.CharField (
        required=True,
        max_length=120,
        label = "Name")

    authors=forms.MultipleChoiceField(
        choices=models.Author.objects.all,
        label = "Authors", 
        required=True)

    price=forms.IntegerField(
        required=True,
        label = "Price")

    publisher=forms.CharField (
        required=True,
        max_length=120,
        label = "Publisher")
    #seria = forms.ChoiceField(
    #    choices=models.Seria.objects.all,
    #    label = "Seria", 
    #    required=False
    #)
    genre=forms.ChoiceField(
        choices=models.Genre.GENRE_CHOICES, label = "Genre", required=True)
   
    date_published=forms.DateField(
        required=True,
        widget=forms.SelectDateWidget,
        label = "Date published")

    pages=forms.IntegerField(
        required=True,
        label = "Pages")

    cover=forms.ChoiceField(
        choices=models.Cover.COVER_CHOICES, label = "Cover", required=True)

    format= forms.CharField (
            label = "Format",
            help_text="Please use the following format: width(cm) x length(cm): ")

    #format= forms.MultiValueField (
    #   fields=(forms, forms.IntegerField(label = 'width(cm)'), forms.IntegerField(label = 'length(cm)')),
    #   label = "Format",
    #   error_messages = "Incomplete")

    isbn= forms.CharField (
            label = "ISBN",
            help_text="Please use the following format: 000-000-0000-00-0' ")

    weight=forms.IntegerField(
        required=True,
        label = "Weight")
    
    cover=forms.ChoiceField(
        choices=models.Cover.COVER_CHOICES, label = "Cover", required=True)

    age_restriction=forms.ChoiceField(
        choices=models.AgeRestriction.AGE_RESTRICT_CHOICES, label = "Age restrictions", required=True)

    items_available=forms.IntegerField(
        required=True,
        label = "Items available")

    order_status=forms.ChoiceField(
        choices=[(models.ACTIVE,'Active'), (models.INACTIVE,'Inactive')],
        label = "Order choises", 
        required=True)

    rate=forms.DecimalField (
        required=False,
        label = "Items available")

    description=forms.CharField(
        widget=forms.Textarea,
        required=False,
        label = "Description")

class BookSearchForm(forms.Form):
    search_text =  forms.CharField(
        required = False,
        label='Search by name',
        widget=forms.TextInput(attrs={'placeholder': 'search here!'})
    )

src/forecast/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from random import randint
from forecast import forms
from requests import post
from . import models 
from django.views.generic import ListView, TemplateView, DetailView, CreateView, DeleteView


def show_forecast_view(request):
    NAMES = (request.user, 'Nik', 'Mike', 'Rosenkranz', 'Güldenstern') 
    username=NAMES[randint(0,4)]
    PREDICTIONS =('The night is dark and full of terrors','So long, and thanks for all the fish', 
                   'Don_t Panic', 'Something is rotten in the state of Denmark')
    forecast=PREDICTIONS[randint(0,3)]
    return HttpResponse (f"<h1>{forecast}, {username} </h1>")

class MapPage(TemplateView):
    template_name='forecast/map.html'
    
class BookPage(ListView):
    template_name='forecast/books_list.html'
    model=models.Book
    def get_queryset(self):
        qs=self.model.objects.all()
        return qs
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

class BookDetailView(DetailView):
    template_name='forecast/book_view.html'
    model=models.Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    

class BookAdd(CreateView):
    template_name='forecast/book_add.html'
    model=models.Book
    fields = '__all__'
    def get_success_url(self):
        return f'book/{object.pk}'


class DeleteBook(DeleteView):
    template_name='forecast/book_delete.html'
    model=models.Book
    def get_success_url(self):
        return f'book/{object.pk}'

class MainPage(ListView):
    template_name='forecast/main_page.html'
    model=models.Book
    def get_queryset(self):
        qs=self.model.objects.all()
        return qs
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

class MainPageThanks(ListView):
    template_name='forecast/main_page_thanks.html'
    model=models.Book
    def get_queryset(self):
        qs=self.model.objects.all()
        return qs
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

class NavBar(TemplateView):
    template_name='forecast/navbar.html'

class BookSearch(ListView):
    template_name='forecast/books_search.html'
    model=models.Book
    def get_queryset(self):
        q=self.request.GET.get('search_query')
        if q: 
            qs = self.model.objects.filter(name__contains = q)
        else: 
            qs = []
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

class NewArrivals(ListView):
    template_name='forecast/new_arrivals.html'
    model=models.Book
    def get_queryset(self):
        qs=self.model.objects.all()
        return qs
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

class Bestsellers(ListView):
    template_name='forecast/bestsellers.html'
    model=models.Book
    def get_queryset(self):
        qs=self.model.objects.all()
        return qs
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

class Catalogue(ListView):
    template_name='forecast/catalogue.html'
    model=models.Book
    def get_queryset(self):
        qs=self.model.objects.all()
        return qs
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

src/forecast/templates/forecast/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head class="p-3 mb-2 bg-dark text-white">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static '/js/bootstrap.bundle.min.js' %}" > </script>
    <title class="p-3 mb-2 bg-dark text-white">{% block title%} {% endblock title%}</title>
</head>

<body background="black" class="p-3 mb-2 bg-dark text-white">
    {% include 'forecast/horizontal_line.html' %}
    <h1 class="p-3 mb-2 bg-dark text-white"> {% block header %}{% endblock header  %} </h1>
    {% include 'forecast/horizontal_line.html' %}
    {% block body %}{% endblock body %}
</body>
</html>

src/forecast/templates/forecast/bestsellers.html
{% extends 'reference/base.html' %}
{% block title %} Bestsellers {% endblock title %}
{% block header  %}  {% endblock header %}
{% block  body %}
<h1 class="nav-item"> Bestsellers {{ object.headline }} </h1>
<!--filter on data add-->
<table class="table table-bordered table-dark" > 
    <tr>
        <td> name</td>
        <td> details </td> 
        <td> price </td>
        <td> description </td>
    </tr>
    {% for obj in object_list|slice:":3"%}
    <tr><td> {{obj.pk}} {{obj.name}} </td>
        <td> <a href="/book/{{obj.id}}"> Details </a>  </td>
        <td> {{obj.price}} </td>
        <td> {{obj.description}} </td>
    </tr>
    {% endfor %}
</table>
{% endblock body %}

src/forecast/templates/forecast/book_add.html
{% extends 'forecast/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add a book {% endblock title %}
{% block head  %} Add a book{% endblock head %}

{% block  body %}

<form action="" method="post"  class="p-3 mb-2 bg-dark text-white">
    {% csrf_token %}
    {{ form | crispy }} <br>
    <input type="submit" class="btn btn-primary">
   
{% endblock body %}

src/forecast/templates/forecast/book_delete.html
<!DOCTYPE html>
<html lang="en">
<head> {{book.name}} </head>
<body>

<h1>{{book.name}}</h1>
<b> </b>


</body>
</html>

src/forecast/templates/forecast/book_view.html
{% extends 'forecast/base.html' %}
{% block title %} {{book.name}} {% endblock title %}
{% block head  %} {{book.authors.name}} {% endblock head %}

{% block  body %}
<img src='{{book.image}}' class="rounded float-end" >
<h1>{{book.name}}</h1>
<b> {{book.content}}<br>
<b> Genre </b> {{book.genre}}<br>
<b> Name </b> {{book.name}}<br>
<b> Author(s) </b> {{book.authors}}<br>
<b> Publisher </b> {{book.publisher}}<br>
<b> Date published </b> {{book.date_published}}<br>
<b> Pages </b> {{book.pages}}<br>
<b> Cover </b> {{book.cover}}<br>
<b> Format </b> {{book.format}}<br>
<b> ISBN </b> {{book.isbn}}<br>
<b> Weight </b> {{book.weight}}<br>
<b> Age restriction </b> {{book.age_restriction}}<br>
<b> Items available </b> {{book.items_available}}<br>
<b> Order status </b> {{book.order_status}}<br>
<b> Rate </b> {{book.rate}}<br>
<b> Description </b> {{book.description}}<br>
<div class="p-3 mb-2 bg-dark text-white"style = "width: 18rem;"> 
    <div class = "card-body">
        <h5 class = "card-title"> {{book.name}} {{book.authors.name}} </h5>
        <p class = "card-text" name = "price"> {{book.price}} BYN</p>
        <form action = "{% url 'order:add_to_cart' %}" method = "get" >
            {% csrf_token%}
            <input type = "hidden" name = "book_id" value ={{object.pk}}>
                <div class="form-group-row">
                  <div class="col-md-8">
                    <input type="number" class="form-control" name = "quantity" min='1' max = '100' step = '1'> 
                </div>
                    <div class="col-md-4">
                    <div class="col-auto my-1" value = "1" >
                        <input type="submit" class="btn btn-primary" value = "Add to Cart">
                    </div>
                </div>
              </form>


{% endblock body %}

src/forecast/templates/forecast/books_list.html
{% extends 'reference/base.html' %}
{% block title %} Books list {% endblock title %}
{% block head  %} Books list {% endblock head %}

{% block  body %}

<table class="table table-success table-striped" border="1"> 
    <tr>
        <td> name</td>
        <td> cover </td>
        <td> details </td> 
        <td> price </td>
        <td> description </td>
    </tr>
    {% for obj in object_list %}
    <tr><td> {{obj.pk}} {{obj.name}} </td>
        <td> <img src="{{obj.image}}"> </td>
        <td> <a href="{{ obj.get_absolute_url }}"> <i class="bi bi-info-square-fill"> </i> </a>  </td>
        <td> {{obj.price}} </td>
        <td> {{obj.description}} </td>
            
    </tr>
    {% endfor %}
</table>

{% endblock body %}

src/forecast/templates/forecast/books_search.html
{% extends 'reference/base.html' %}
{% block title %} Books search {% endblock title %}
{% block header  %} Books search {% endblock header %}

{% block  body %}
    <form action = '' method = "GET">
        <div class="input-group">
            <input name = 'search_query' type="search" class="form-control rounded" placeholder="Search a book" aria-label="Search" aria-describedby="search-addon" width = '20' />
            <button type="submit" class="btn btn-outline-primary">search</button>
          </div>
    </form>

   <h2> Results </h2> 
   {% for book in object_list%}
   <a href="{{ book.get_absolute_url }}"> {{book.name}} </a> 
   {% endfor %}

   {% endblock body %}

src/forecast/templates/forecast/catalogue.html
{% extends 'reference/base.html' %}
{% block title %} Catalogue {% endblock title %}
{% block header  %}  {% endblock header %}
{% block  body %}
<h1 class="nav-item"> Catalogue {{ object.headline }} </h1>
<!--filter on data add-->
<table class="table table-bordered table-dark" > 
    <tr>
        <td> name</td>
        <td> details </td> 
        <td> price </td>
        <td> description </td>
    </tr>
    {% for obj in object_list  %}
    <tr><td> {{obj.pk}} {{obj.name}} </td>
        <td> <a href="/book/{{obj.id}}"> Details </a>  </td>
        <td> {{obj.price}} </td>
        <td> {{obj.description}} </td>
    </tr>
    {% endfor %}
</table>
{% endblock body %}

src/forecast/templates/forecast/main_page.html
{% extends 'reference/base.html' %}
{% block title %} Babel Library {% endblock title %}
{% block header  %} 
<header class="p-3 mb-2 bg-dark text-white">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/new_arrivals/">New arrivals</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/catalogue/">Catalogue</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="/bestsellers/">Bestsellers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/book_search/" >Search</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/map_page/">Map</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->
  
    <!-- Background image -->
    <div
      class="p-5 text-center bg-image"
      src="picture.webp"
      style="
        background-image: url('https://images.unsplash.com/photo-1545244100-07c99f4d0492?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80');
        height: 1000px;
      "
    >
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="d-flex justify-content-center align-items-center h-100">
          <div class="text-white">
            <h1 class="mb-3">Babel library</h1>
            <h4 class="mb-3">only best books</h4>
            <a class="btn btn-outline-light btn-lg" href="/book_search/" role="button"
            >Search</a
            >
          </div>
        </div>
      </div>
    </div>
    <!-- Background image -->
  </header>
  {% endblock header %}
{% block  body %}

{% endblock body %}

src/forecast/templates/forecast/main_page_thanks.html
{% extends 'reference/base.html' %}
{% block title %} Babel Library {% endblock title %}
{% block header  %} 
<header class="p-3 mb-2 bg-dark text-white">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="/new_arrivals/">New arrivals</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/catalogue/">Catalogue</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="/bestsellers/">Bestsellers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/book_search/" >Search</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/map_page/">Map</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->
  
    <!-- Background image -->
    <div
      class="p-5 text-center bg-image"
      src="picture.webp"
      style="
        background-image: url('https://images.unsplash.com/photo-1545244100-07c99f4d0492?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80');
        height: 1000px;
      "
    >
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="d-flex justify-content-center align-items-center h-100">
          <div class="text-white">
            <h1 class="mb-3">Babel library</h1>
            <h4 class="mb-3">only best books</h4>
            <a class="btn btn-outline-light btn-lg" href="/book_search/" role="button"
            >Search</a
            >
          </div>
        </div>
      </div>
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="d-flex justify-content-center align-items-center h-100">
          <div class="text-white">
            <h1 class="mb-3">Your order created. Thanks!</h1>
          </div>
        </div>
      </div>
    </div>
    <!-- Background image -->
  </header>
  {% endblock header %}
{% block  body %}

{% endblock body %}

src/forecast/templates/forecast/new_arrivals.html
{% extends 'reference/base.html' %}
{% block title %} New arrivals {% endblock title %}
{% block header  %}  {% endblock header %}
{% block  body %}
<h1 class="nav-item" > New arrivals {{ object.headline }} </h1>
<!--filter on data add-->
<table class="table table-bordered table-dark" > 
    <tr>
        <td> name</td>
        <td> details </td> 
        <td> price </td>
        <td> description </td>
    </tr>
    {% for obj in object_list|slice:"3:" %}
    <tr><td> {{obj.pk}} {{obj.name}} </td>
        <td> <a href="/book/{{obj.id}}"> Details </a> </td>
        <td> {{obj.price}} </td>
        <td> {{obj.description}} </td>
    </tr>
    {% endfor %}
</table>
{% endblock body %}